Check for sys/auxv.h before using it.
- fixes uclibc-ng compile (does not provide sys/auxv.h header file)

Fixes:

  haveged.c:22:10: fatal error: sys/auxv.h: No such file or directory
     22 | #include <sys/auxv.h>
        |          ^~~~~~~~~~~~

Signed-off-by: Peter Seiderer <ps.report@gmx.net>